# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - alan-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://smartfarmdockertest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3a5728b74e334e55acbe1ede2c97c6f8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6d2abe7dfe86424ba39c15d6363525bd }}
              
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: ./smart-farm-backend
        push: true
        tags: smartfarmdockertest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3a5728b74e334e55acbe1ede2c97c6f8 }}/app:${{ github.sha }}
        file: ./smart-farm-backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alan-demo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a092e9d375dc429db2a25f353c4dfa60 }}
        images: 'smartfarmdockertest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3a5728b74e334e55acbe1ede2c97c6f8 }}/app:${{ github.sha }}'
